using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore;
using Weymela.Application;
using Weymela.Infrastructure.Operations;
using Weymela.Infrastructure.Persistence;

namespace Weymela.Api;

// Keys are generated by this API and never supplied as route or filesystem parameters.
public sealed class CreatorPhotoStore(RuntimeOptions options)
{
    public async Task<string> SaveAsync(IFormFile photo, CancellationToken ct)
    {
        if (string.IsNullOrEmpty(options.CreatorPhotoDirectory))
            throw new ApplicationFailure(FailureKind.Validation, "Creator photos are unavailable.");
        if (photo.Length is < 1 or > RuntimeOptions.ReceiptBytes ||
            photo.ContentType is not (PrivateReceiptStore.Jpeg or PrivateReceiptStore.Png))
            throw new ApplicationFailure(FailureKind.Validation, "Choose a JPEG or PNG photo smaller than 4 MB.");
        await using var source = photo.OpenReadStream();
        using var buffer = new MemoryStream((int)photo.Length);
        await source.CopyToAsync(buffer, ct);
        var bytes = buffer.ToArray();
        if (bytes.Length != photo.Length || !PrivateReceiptStore.ValidImage(bytes, photo.ContentType))
            throw new ApplicationFailure(FailureKind.Validation, "The photo is invalid. Choose a JPEG or PNG image.");
        var key = "p_" + Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();
        var path = Path.Combine(options.CreatorPhotoDirectory, key);
        var temporary = Path.Combine(options.CreatorPhotoDirectory, "tmp_" + Guid.NewGuid().ToString("N"));
        try
        {
            await using (var target = new FileStream(temporary, FileMode.CreateNew, FileAccess.Write, FileShare.None, 4096, FileOptions.WriteThrough))
            {
                if (OperatingSystem.IsLinux()) File.SetUnixFileMode(temporary, UnixFileMode.UserRead | UnixFileMode.UserWrite);
                await target.WriteAsync(bytes, ct);
                target.Flush(flushToDisk: true);
            }
            File.Move(temporary, path);
            return key;
        }
        finally { if (File.Exists(temporary)) File.Delete(temporary); }
    }

    public async Task<(byte[] Bytes, string ContentType)> ReadAsync(string? key, CancellationToken ct)
    {
        if (!IsKey(key) || string.IsNullOrEmpty(options.CreatorPhotoDirectory))
            throw new ApplicationFailure(FailureKind.NotFound, "Creator photo not found.");
        var path = Path.Combine(options.CreatorPhotoDirectory, key!);
        var file = new FileInfo(path);
        if (!file.Exists || file.LinkTarget is not null || file.Length is < 1 or > RuntimeOptions.ReceiptBytes)
            throw new ApplicationFailure(FailureKind.NotFound, "Creator photo not found.");
        var bytes = await File.ReadAllBytesAsync(path, ct);
        var contentType = PrivateReceiptStore.ValidImage(bytes, PrivateReceiptStore.Jpeg) ? PrivateReceiptStore.Jpeg
            : PrivateReceiptStore.ValidImage(bytes, PrivateReceiptStore.Png) ? PrivateReceiptStore.Png : null;
        if (contentType is null) throw new ApplicationFailure(FailureKind.NotFound, "Creator photo not found.");
        return (bytes, contentType);
    }

    public void Delete(string? key)
    {
        if (IsKey(key) && !string.IsNullOrEmpty(options.CreatorPhotoDirectory))
            File.Delete(Path.Combine(options.CreatorPhotoDirectory, key!));
    }

    // Only old unreferenced files are swept; a concurrent in-flight upload cannot be removed.
    public async Task PruneOrphansAsync(WeymelaDbContext db, CancellationToken ct)
    {
        if (string.IsNullOrEmpty(options.CreatorPhotoDirectory)) return;
        foreach (var path in Directory.EnumerateFiles(options.CreatorPhotoDirectory, "p_*"))
        {
            var file = new FileInfo(path);
            if (!IsKey(file.Name) || file.LinkTarget is not null || file.LastWriteTimeUtc > DateTime.UtcNow.AddDays(-1)) continue;
            if (!await db.PublicWorkspaceProfiles.AsNoTracking().AnyAsync(x => x.CreatorPhotoKey == file.Name, ct))
                File.Delete(path);
        }
    }

    private static bool IsKey(string? key) => key is { Length: 66 } && key.StartsWith("p_", StringComparison.Ordinal)
        && key.AsSpan(2).IndexOfAnyExcept("0123456789abcdef") < 0;
}
