<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../Weymela.Application/Weymela.Application.csproj" /><ProjectReference Include="../Weymela.Infrastructure/Weymela.Infrastructure.csproj" /></ItemGroup></Project>
