// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Weymela.Infrastructure.Persistence;

#nullable disable

namespace Weymela.Infrastructure.Persistence.Migrations;

[DbContext(typeof(WeymelaDbContext))]
[Migration("20260919120000_AddUgcCustomerDiscountLimit")]
partial class AddUgcCustomerDiscountLimit
{
}
