// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Weymela.Infrastructure.Persistence;

#nullable disable

namespace Weymela.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WeymelaDbContext))]
    partial class WeymelaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("v3")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Weymela.Domain.BusinessWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReservedBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("StoredTotalBalance")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalBalance")
                        .HasComputedColumnSql("\"AvailableBalance\" + \"ReservedBalance\"", true);

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("BusinessWallets", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Wallet_NonNegative", "\"AvailableBalance\" >= 0 AND \"ReservedBalance\" >= 0");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.CreatorAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OriginalAllocation")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("StoredRemainingAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("RemainingAmount")
                        .HasComputedColumnSql("\"OriginalAllocation\" - \"UsedAmount\"", true);

                    b.Property<decimal>("UsedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId", "CreatorId")
                        .IsUnique();

                    b.ToTable("CreatorAllocations", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Allocation_Budgets", "\"OriginalAllocation\" > 0 AND \"UsedAmount\" >= 0 AND \"UsedAmount\" <= \"OriginalAllocation\"");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.CreatorApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentConcept")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByBusinessUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId", "CreatorId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Pending', 'Approved')");

                    b.HasIndex("PromotionId", "Status");

                    b.ToTable("CreatorApplications", "v3");
                });

            modelBuilder.Entity("Weymela.Domain.CreatorEarningEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("JournalId");

                    b.HasIndex("PromotionId");

                    b.ToTable("CreatorEarningEntries", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_CreatorEarning_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.CreatorEarningsAccount", b =>
                {
                    b.Property<Guid>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("CreatorId");

                    b.ToTable("CreatorEarningsAccounts", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_CreatorEarnings_NonNegative", "\"AvailableEarnings\" >= 0");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.CreatorPromotionParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BaselineViews")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CreatorAllocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalContentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LatestVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LatestVerifiedViews")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RewardedViewCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("WentLiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatorAllocationId")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalContentId")
                        .IsUnique();

                    b.HasIndex("CreatorAllocationId", "PromotionId", "CreatorId");

                    b.ToTable("CreatorPromotionParticipations", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Participation_Views", "\"BaselineViews\" >= 0 AND \"LatestVerifiedViews\" >= \"BaselineViews\" AND \"RewardedViewCount\" >= 0 AND \"RewardedViewCount\" <= \"LatestVerifiedViews\" - \"BaselineViews\"");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.CustomerCashbackAccount", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableCashback")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerCashbackAccounts", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Cashback_NonNegative", "\"AvailableCashback\" >= 0");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.CustomerCashbackEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("VerifiedSaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JournalId");

                    b.HasIndex("VerifiedSaleId");

                    b.ToTable("CustomerCashbackEntries", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Cashback_PositiveSale", "\"Amount\" > 0 AND (\"Source\" <> 'VerifiedSale' OR \"VerifiedSaleId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.FinancialJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyReference")
                        .HasColumnType("text");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdempotencyReference");

                    b.HasIndex("PromotionId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("SourceType");

                    b.ToTable("FinancialJournals", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Journal_Posted", "\"IsPosted\"");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.FinancialJournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Account");

                    b.HasIndex("JournalId");

                    b.ToTable("FinancialJournalLines", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_JournalLine_Positive", "\"Amount\" > 0 AND \"Type\" IN ('Debit', 'Credit')");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.LegalAcceptance", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpReference")
                        .HasColumnType("text");

                    b.Property<string>("UserAgentReference")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Role", "DocumentVersionId");

                    b.HasIndex("DocumentVersionId");

                    b.ToTable("LegalAcceptances", "v3");
                });

            modelBuilder.Entity("Weymela.Domain.LegalDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type", "EffectiveFromUtc");

                    b.HasIndex("Type", "Version")
                        .IsUnique();

                    b.ToTable("LegalDocumentVersions", "v3");
                });

            modelBuilder.Entity("Weymela.Domain.OfferQrSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorAllocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasFilter("\"Status\"='Issued'");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("CustomerId", "IssuedAtUtc");

                    b.HasIndex("CreatorAllocationId", "PromotionId", "CreatorId");

                    b.ToTable("OfferQrSessions", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Qr_Expiry", "\"ExpiresAtUtc\" = \"IssuedAtUtc\" + INTERVAL '5 minutes'");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.PayoutRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Beneficiary")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EligibleAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PaidBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("ThresholdUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("CreatorId")
                        .IsUnique()
                        .HasFilter("\"Status\"='Eligible' AND \"CreatorId\" IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("\"Status\"='Eligible' AND \"CustomerId\" IS NOT NULL");

                    b.HasIndex("JournalId");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasFilter("\"Reference\" IS NOT NULL");

                    b.ToTable("PayoutRecords", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Payout_Amounts", "\"Amount\" > 0 AND \"Amount\" = \"ThresholdUsed\" AND ((\"Beneficiary\"='Creator' AND \"CreatorId\" IS NOT NULL AND \"CustomerId\" IS NULL) OR (\"Beneficiary\"='Customer' AND \"CustomerId\" IS NOT NULL AND \"CreatorId\" IS NULL))");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.PlatformRevenueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("Source", "CreatedAtUtc");

                    b.ToTable("PlatformRevenueEntries", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Revenue_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.PlatformSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SettledBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("PlatformSettlements", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Settlement_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PromotionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PublicPromotionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ReservedBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("StoredAllocatedBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("AllocatedBudget");

                    b.Property<decimal>("StoredRemainingBudget")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("RemainingBudget")
                        .HasComputedColumnSql("\"TotalBudget\" - \"UsedBudget\"", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UsedBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PublicPromotionId")
                        .IsUnique();

                    b.HasIndex("BusinessId", "Status");

                    b.ToTable("Promotions", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Promotion_Budgets", "\"TotalBudget\" > 0 AND \"ReservedBudget\" >= 0 AND \"UsedBudget\" >= 0 AND \"ReservedBudget\" + \"UsedBudget\" <= \"TotalBudget\" AND \"AllocatedBudget\" >= \"UsedBudget\" AND \"AllocatedBudget\" <= \"TotalBudget\"");

                            t.HasCheckConstraint("CK_Promotion_Dates", "\"EndDateUtc\" > \"StartDateUtc\"");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.PromotionViewVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorAllocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<long>("CurrentVerifiedViews")
                        .HasColumnType("bigint");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalContentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalPlatform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParticipationId")
                        .HasColumnType("uuid");

                    b.Property<long>("PreviousVerifiedViews")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ReportedViews")
                        .HasColumnType("bigint");

                    b.Property<long>("RewardedViewCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ParticipationId");

                    b.HasIndex("CreatorAllocationId", "PromotionId", "CreatorId");

                    b.ToTable("PromotionViewVerifications", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Views_Valid", "\"PreviousVerifiedViews\" >= 0 AND \"CurrentVerifiedViews\" >= \"PreviousVerifiedViews\" AND \"RewardedViewCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.VerifiedSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorAllocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreatorCommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CustomerCashbackAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlatformRevenueAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PurchaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("QrTokenReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("TotalPromotionCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("BusinessId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("CreatorAllocationId", "PromotionId", "CreatorId");

                    b.ToTable("VerifiedSales", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Sale_Amounts", "\"PurchaseAmount\" > 0 AND \"CreatorCommissionAmount\" >= 0 AND \"CustomerCashbackAmount\" >= 0 AND \"PlatformRevenueAmount\" >= 0 AND \"TotalPromotionCharge\" = \"CreatorCommissionAmount\" + \"CustomerCashbackAmount\" + \"PlatformRevenueAmount\"");
                        });
                });

            modelBuilder.Entity("Weymela.Domain.ViewRewardReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Blocks")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BusinessCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreatorEarning")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlatformEarning")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("RewardedThrough")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("ParticipationId", "RewardedThrough")
                        .IsUnique();

                    b.ToTable("ViewRewardReceipts", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_ViewReward_Amounts", "\"Blocks\" > 0 AND \"RewardedThrough\" > 0 AND \"BusinessCharge\" > 0 AND \"BusinessCharge\" = \"CreatorEarning\" + \"PlatformEarning\"");
                        });
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("PromotionId", "OccurredAtUtc");

                    b.ToTable("AuditEvents", "v3");
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.CommercePermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCheckout")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "Role", "SubjectId");

                    b.HasIndex("SubjectId", "Role", "IsActive");

                    b.ToTable("CommercePermissions", "v3");
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.DepositRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProofReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("Provider", "ConfirmationReference")
                        .IsUnique()
                        .HasFilter("\"Status\"='Approved'");

                    b.HasIndex("Status", "SubmittedAtUtc");

                    b.HasIndex("BusinessId", "Provider", "ExternalReference")
                        .IsUnique();

                    b.ToTable("DepositRequests", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_DepositRequest_Journal", "(\"Status\"='Approved' AND \"JournalId\" IS NOT NULL) OR (\"Status\" IN ('Pending','Rejected') AND \"JournalId\" IS NULL)");

                            t.HasCheckConstraint("CK_DepositRequest_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_DepositRequest_Review", "(\"Status\"='Pending' AND \"ReviewedBy\" IS NULL AND \"ReviewedAtUtc\" IS NULL) OR (\"Status\" IN ('Approved','Rejected') AND \"ReviewedBy\" IS NOT NULL AND \"ReviewedAtUtc\" IS NOT NULL AND \"ConfirmationReference\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.FinancialConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FinancialConfigurations", "v3");
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.FinancialConfigurationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreatorPayoutThreshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CustomerPayoutThreshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId", "Version")
                        .IsUnique();

                    b.HasIndex("EffectiveFromUtc", "Version");

                    b.ToTable("FinancialConfigurationVersions", "v3");
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.IdentityBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidAfterUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Provider", "ProjectId", "ExternalSubject")
                        .IsUnique();

                    b.ToTable("IdentityBindings", "v3");
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.InAppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastPushErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("NextPushAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PushAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PushState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("NextPushAtUtc")
                        .HasFilter("\"PushState\"='Pending'");

                    b.HasIndex("UserId", "Role", "CreatedAtUtc");

                    b.HasIndex("UserId", "Role", "SourceKey")
                        .IsUnique();

                    b.ToTable("InAppNotifications", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Notification_ReadTime", "\"ReadAtUtc\" IS NULL OR \"ReadAtUtc\" >= \"CreatedAtUtc\"");
                        });
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecipientCursor")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAtUtc")
                        .HasFilter("\"ProcessedAtUtc\" IS NULL AND \"FailedAtUtc\" IS NULL");

                    b.HasIndex("OccurredAtUtc")
                        .HasFilter("\"ProcessedAtUtc\" IS NULL");

                    b.ToTable("OutboxMessages", "v3");
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.PromotionBudgetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("JournalId");

                    b.HasIndex("PromotionId", "CreatedAtUtc");

                    b.ToTable("PromotionBudgetEntries", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetEntry_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.PromotionReservation", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("PromotionId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("JournalId");

                    b.ToTable("PromotionReservations", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_Positive", "\"OriginalAmount\" > 0");
                        });
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.PublicWorkspaceProfile", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DirectionsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("SocialVerified")
                        .HasColumnType("boolean");

                    b.Property<long>("VerifiedFollowers")
                        .HasColumnType("bigint");

                    b.Property<long>("VerifiedViews")
                        .HasColumnType("bigint");

                    b.HasKey("SubjectId", "Role");

                    b.HasIndex("Role", "PublicId")
                        .IsUnique();

                    b.ToTable("PublicWorkspaceProfiles", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_PublicProfile_Metrics", "\"VerifiedFollowers\" >= 0 AND \"VerifiedViews\" >= 0");
                        });
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.StoredIdempotencyRecord", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActorId", "OperationType", "Key");

                    b.ToTable("IdempotencyRecords", "v3");
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.WalletEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("BusinessId", "CreatedAtUtc");

                    b.ToTable("WalletEntries", "v3", t =>
                        {
                            t.HasCheckConstraint("CK_WalletEntry_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.WorkerCheckpoint", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("LastEffectiveConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Name");

                    b.ToTable("WorkerCheckpoints", "v3");
                });

            modelBuilder.Entity("Weymela.Domain.CreatorAllocation", b =>
                {
                    b.HasOne("Weymela.Domain.Promotion", null)
                        .WithMany("Allocations")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.CreatorApplication", b =>
                {
                    b.HasOne("Weymela.Domain.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.CreatorEarningEntry", b =>
                {
                    b.HasOne("Weymela.Domain.CreatorEarningsAccount", null)
                        .WithMany("Entries")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Weymela.Domain.CreatorPromotionParticipation", b =>
                {
                    b.HasOne("Weymela.Domain.CreatorAllocation", null)
                        .WithMany()
                        .HasForeignKey("CreatorAllocationId", "PromotionId", "CreatorId")
                        .HasPrincipalKey("Id", "PromotionId", "CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.CustomerCashbackEntry", b =>
                {
                    b.HasOne("Weymela.Domain.CustomerCashbackAccount", null)
                        .WithMany("Entries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.VerifiedSale", null)
                        .WithMany()
                        .HasForeignKey("VerifiedSaleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Weymela.Domain.FinancialJournal", b =>
                {
                    b.HasOne("Weymela.Domain.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Weymela.Domain.FinancialJournalLine", b =>
                {
                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.LegalAcceptance", b =>
                {
                    b.HasOne("Weymela.Domain.LegalDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.OfferQrSession", b =>
                {
                    b.HasOne("Weymela.Domain.VerifiedSale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weymela.Domain.CreatorAllocation", null)
                        .WithMany()
                        .HasForeignKey("CreatorAllocationId", "PromotionId", "CreatorId")
                        .HasPrincipalKey("Id", "PromotionId", "CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.PayoutRecord", b =>
                {
                    b.HasOne("Weymela.Infrastructure.Persistence.Records.FinancialConfigurationVersion", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.CreatorEarningsAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weymela.Domain.CustomerCashbackAccount", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Weymela.Domain.PlatformRevenueEntry", b =>
                {
                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Weymela.Domain.PlatformSettlement", b =>
                {
                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.Promotion", b =>
                {
                    b.HasOne("Weymela.Domain.BusinessWallet", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .HasPrincipalKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Weymela.Domain.CreatorEligibilityCriteria", "Eligibility", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .HasColumnType("text");

                            b1.Property<string>("Market")
                                .HasColumnType("text");

                            b1.Property<long?>("MinimumVerifiedFollowers")
                                .HasColumnType("bigint");

                            b1.Property<string>("Requirements")
                                .HasColumnType("text");

                            b1.HasKey("PromotionId");

                            b1.ToTable("Promotions", "v3");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId");
                        });

                    b.OwnsOne("Weymela.Domain.PricingSnapshot", "PricingSnapshot", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BusinessCharge")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<Guid>("ConfigurationVersionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CreatorCommissionPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<decimal>("CreatorEarning")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("CustomerCashbackPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<DateTime>("EffectiveFromUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal?>("MinimumPromotionBudget")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("PlatformEarning")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("PlatformPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<string>("PromotionType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<int>("ViewsPerReward")
                                .HasColumnType("integer");

                            b1.HasKey("PromotionId");

                            b1.ToTable("PricingSnapshots", "v3");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId");
                        });

                    b.Navigation("Eligibility")
                        .IsRequired();

                    b.Navigation("PricingSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.PromotionViewVerification", b =>
                {
                    b.HasOne("Weymela.Domain.CreatorPromotionParticipation", null)
                        .WithMany()
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weymela.Domain.CreatorAllocation", null)
                        .WithMany()
                        .HasForeignKey("CreatorAllocationId", "PromotionId", "CreatorId")
                        .HasPrincipalKey("Id", "PromotionId", "CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.VerifiedSale", b =>
                {
                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.CreatorAllocation", null)
                        .WithMany()
                        .HasForeignKey("CreatorAllocationId", "PromotionId", "CreatorId")
                        .HasPrincipalKey("Id", "PromotionId", "CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.ViewRewardReceipt", b =>
                {
                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.CreatorPromotionParticipation", null)
                        .WithMany()
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.DepositRequest", b =>
                {
                    b.HasOne("Weymela.Domain.BusinessWallet", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .HasPrincipalKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.FinancialConfigurationVersion", b =>
                {
                    b.HasOne("Weymela.Infrastructure.Persistence.Records.FinancialConfiguration", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Weymela.Domain.PricingSnapshot", "ViewOnly", b1 =>
                        {
                            b1.Property<Guid>("FinancialConfigurationVersionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BusinessCharge")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<Guid>("ConfigurationVersionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CreatorCommissionPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<decimal>("CreatorEarning")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("CustomerCashbackPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<DateTime>("EffectiveFromUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal?>("MinimumPromotionBudget")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("PlatformEarning")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("PlatformPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<string>("PromotionType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<int>("ViewsPerReward")
                                .HasColumnType("integer");

                            b1.HasKey("FinancialConfigurationVersionId");

                            b1.ToTable("FinancialConfigurationVersions", "v3");

                            b1.WithOwner()
                                .HasForeignKey("FinancialConfigurationVersionId");
                        });

                    b.OwnsOne("Weymela.Domain.PricingSnapshot", "ViewPlusCommission", b1 =>
                        {
                            b1.Property<Guid>("FinancialConfigurationVersionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BusinessCharge")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<Guid>("ConfigurationVersionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CreatorCommissionPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<decimal>("CreatorEarning")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("CustomerCashbackPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<DateTime>("EffectiveFromUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal?>("MinimumPromotionBudget")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("PlatformEarning")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("PlatformPercent")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)");

                            b1.Property<string>("PromotionType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<int>("ViewsPerReward")
                                .HasColumnType("integer");

                            b1.HasKey("FinancialConfigurationVersionId");

                            b1.ToTable("FinancialConfigurationVersions", "v3");

                            b1.WithOwner()
                                .HasForeignKey("FinancialConfigurationVersionId");
                        });

                    b.Navigation("ViewOnly")
                        .IsRequired();

                    b.Navigation("ViewPlusCommission")
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.PromotionBudgetEntry", b =>
                {
                    b.HasOne("Weymela.Domain.CreatorAllocation", null)
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.PromotionReservation", b =>
                {
                    b.HasOne("Weymela.Domain.BusinessWallet", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .HasPrincipalKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.Promotion", null)
                        .WithOne()
                        .HasForeignKey("Weymela.Infrastructure.Persistence.Records.PromotionReservation", "PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Infrastructure.Persistence.Records.WalletEntry", b =>
                {
                    b.HasOne("Weymela.Domain.BusinessWallet", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .HasPrincipalKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weymela.Domain.FinancialJournal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Weymela.Domain.CreatorEarningsAccount", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Weymela.Domain.CustomerCashbackAccount", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Weymela.Domain.FinancialJournal", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Weymela.Domain.Promotion", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
