import { expect, test } from "@playwright/test";
import { layout, login, open } from "./helpers";

test("Business sees the Promotion shortfall before publishing an unfunded Promotion", async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await login(context, "business");
  const before = await (await context.request.get("/api/business/wallet")).json() as { available: number; reserved: number };
  const title = `Funding gate ${Date.now()}`;
  await page.goto("/business/campaigns/new?type=views-sales");
  await expect(page.getByRole("heading", { name: "Create Promotion" })).toBeVisible();
  await page.getByLabel("Promotion title").fill(title);
  await page.getByLabel("Application closes").fill(new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10));
  await page.getByLabel("Content due").fill(new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10));
  await page.getByRole("button", { name: "Add TikTok Creator slot" }).click();
  await page.getByLabel("Promotion budget").fill(String(before.available + 1000));
  const draftNotice = page.locator(".notice").filter({ hasText: "before posting it to Creators" });
  await expect(draftNotice).toContainText("1,000 ETB");
  await expect(page.getByRole("button", { name: "Save Draft", exact: true })).toBeEnabled();
  await layout(page);
  await page.getByRole("button", { name: "Save Draft", exact: true }).click();
  await expect(page).toHaveURL(/\/business\/campaigns\/[0-9a-f-]{36}$/i);
  await expect(page.getByRole("button", { name: "Fund Promotion", exact: true })).toBeDisabled();
  const fundingNotice = page.locator(".callout .notice");
  await expect(fundingNotice).toContainText("1,000 ETB more");
  await expect(fundingNotice.getByRole("link", { name: "Add Funds" })).toHaveAttribute("href", "/business/wallet");
  const after = await (await context.request.get("/api/business/wallet")).json() as { available: number; reserved: number };
  expect(after.available).toBe(before.available);
  expect(after.reserved).toBe(before.reserved);
  await layout(page);
});
