using System;
using Weymela.Domain;
using Xunit;

namespace Weymela.Domain.Tests;

public sealed class DomainModelTests
{
    private static readonly DateTime Now = new(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);
    private static PricingSnapshot Pricing(PromotionType type) => new(type, 1000, new Money(300), new Money(200), new Money(100), 4.5m, 2m, 3.5m, Now, Guid.NewGuid());
    private static Promotion Promotion(PromotionType type = PromotionType.ViewOnly) => new(Guid.NewGuid(), "Test promotion", "Brief", type, new Money(6000), new(null, null, "ET", "requirements"), Now, Now.AddDays(30), Pricing(type), Now, 30);

    [Fact] public void Deposit_must_be_positive_and_preserves_wallet_invariant() { var w = new BusinessWallet(Guid.NewGuid()); Assert.Throws<ArgumentOutOfRangeException>(() => w.CreditDeposit(new Money(0), Now, Guid.NewGuid())); w.CreditDeposit(new Money(10000), Now, Guid.NewGuid()); Assert.Equal(10000m, w.TotalBalance.Amount); Assert.Equal(10000m, w.AvailableBalance.Amount); Assert.Equal(0m, w.ReservedBalance.Amount); }
    [Fact] public void Reservation_rejects_insufficient_available_and_isolated_balances() { var w = new BusinessWallet(Guid.NewGuid()); w.CreditDeposit(new Money(10000), Now, Guid.NewGuid()); var a = Promotion(); a.Fund(w, Now, Guid.NewGuid()); Assert.Equal(4000m, w.AvailableBalance.Amount); Assert.Equal(6000m, w.ReservedBalance.Amount); Assert.Throws<InvalidOperationException>(() => Promotion().Fund(w, Now, Guid.NewGuid())); }
    [Fact] public void Effective_promotion_type_minimum_is_enforced_without_business_type_thresholds() { var pricing = Pricing(PromotionType.ViewOnly) with { MinimumPromotionBudget = new Money(1000) }; Assert.Throws<InvalidOperationException>(() => new Promotion(Guid.NewGuid(), "Too small", "", PromotionType.ViewOnly, new Money(999), new(null, null, null, null), Now, Now.AddDays(1), pricing, Now, 30)); }
    [Fact] public void Promotion_requires_funding_before_publish_and_enforces_transitions() { var p = Promotion(); Assert.Throws<InvalidOperationException>(() => p.Publish(Now, Guid.NewGuid())); var w = new BusinessWallet(Guid.NewGuid()); w.CreditDeposit(new Money(6000), Now, Guid.NewGuid()); p.Fund(w, Now, Guid.NewGuid()); p.Publish(Now, Guid.NewGuid()); p.Activate(Now, Guid.NewGuid()); Assert.Equal(PromotionStatus.Active, p.Status); }
    [Fact] public void Applications_only_target_published_or_active_and_duplicates_are_application_policy() { var p = Promotion(); Assert.Throws<InvalidOperationException>(() => new CreatorApplication(p.Id, Guid.NewGuid(), null, null, p, Now, Guid.NewGuid())); var w = new BusinessWallet(Guid.NewGuid()); w.CreditDeposit(new Money(6000), Now, Guid.NewGuid()); p.Fund(w, Now, Guid.NewGuid()); p.Publish(Now, Guid.NewGuid()); var app = new CreatorApplication(p.Id, Guid.NewGuid(), "join", null, p, Now, Guid.NewGuid()); app.Approve(Guid.NewGuid(), Now); Assert.Equal(CreatorApplicationStatus.Approved, app.Status); }
    [Fact] public void Allocation_is_bounded_and_cannot_go_negative() { var p = Promotion(); var w = new BusinessWallet(Guid.NewGuid()); w.CreditDeposit(new Money(6000), Now, Guid.NewGuid()); p.Fund(w, Now, Guid.NewGuid()); p.Publish(Now, Guid.NewGuid()); var a = p.Allocate(Guid.NewGuid(), new Money(2500), Now, Guid.NewGuid()); Assert.Throws<InvalidOperationException>(() => p.Allocate(Guid.NewGuid(), new Money(4000), Now, Guid.NewGuid())); p.Activate(Now, Guid.NewGuid()); p.Consume(a.Id, new Money(2500), Now, Guid.NewGuid()); Assert.Equal(0m, a.RemainingAmount.Amount); Assert.Throws<InvalidOperationException>(() => p.Consume(a.Id, new Money(1), Now, Guid.NewGuid())); }
    [Fact] public void View_only_rejects_verified_sales_and_hybrid_accepts() { var view = Promotion(); Assert.Throws<InvalidOperationException>(() => new VerifiedSale(view, Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), new Money(100), new Money(4), new Money(2), new Money(3), "qr", "key", Now)); var hybrid = Promotion(PromotionType.ViewPlusCommission); var sale = new VerifiedSale(hybrid, Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), new Money(100), new Money(4), new Money(2), new Money(3), "qr", "key", Now); Assert.Equal(9m, sale.TotalPromotionCharge.Amount); }
    [Fact] public void Earnings_accumulate_and_journal_is_immutable_and_balanced() { var e = new CreatorEarningsAccount(Guid.NewGuid()); e.Earn(new Money(1200), EarningSource.ViewReward, Guid.NewGuid(), Now, Guid.NewGuid()); e.Earn(new Money(900), EarningSource.SaleCommission, Guid.NewGuid(), Now, Guid.NewGuid()); Assert.Equal(2100m, e.AvailableEarnings.Amount); var j = new FinancialJournal("ref", Guid.NewGuid(), null, JournalSourceType.ViewReward, Now); j.AddLine(JournalLineType.Debit, new Money(100), "reserve"); j.AddLine(JournalLineType.Credit, new Money(100), "creator"); j.Post(); Assert.Throws<InvalidOperationException>(() => j.AddLine(JournalLineType.Debit, new Money(1), "x")); }
    [Fact] public void Legal_acceptance_tracks_document_version_and_role() { var version = new LegalDocumentVersion(Guid.NewGuid(), LegalDocumentType.AntiCircumventionAgreement, "v1", "hash", Now); var acceptance = new LegalAcceptance(Guid.NewGuid(), LegalRole.Creator, version.Id, Now, "ip-ref", "ua-ref"); Assert.Equal(version.Id, acceptance.DocumentVersionId); }
}
