using Weymela.Domain;
namespace Weymela.Application;
public interface ICreatorApplicationRepository { Task<CreatorApplication?> FindActiveAsync(Guid promotionId, Guid creatorId, CancellationToken ct); Task AddAsync(CreatorApplication application, CancellationToken ct); Task<CreatorApplication?> GetAsync(Guid id, CancellationToken ct); Task SaveAsync(CreatorApplication application, CancellationToken ct); }
public interface IAllocationRepository { Task<CreatorAllocation?> GetAsync(Guid id, CancellationToken ct); Task AddAsync(CreatorAllocation allocation, CancellationToken ct); Task SaveAsync(CreatorAllocation allocation, long expectedVersion, CancellationToken ct); }
public sealed class ParticipationApplicationService(IPromotionRepository promotions, ICreatorApplicationRepository applications, IAllocationRepository allocations, IEventPublisher events)
{
 public async Task<CreatorApplication> ApplyAsync(ApplyToPromotionCommand c, CancellationToken ct){if(c.Actor.Role!=ActorRole.Creator)throw new ApplicationFailure(FailureKind.Forbidden,"Only a Creator may apply.");var p=await promotions.GetAsync(c.PromotionId,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Promotion was not found.");if(p.Status is not (PromotionStatus.Published or PromotionStatus.Active)||p.RemainingBudget.Amount<=0)throw new ApplicationFailure(FailureKind.Validation,"Promotion is not eligible for applications.");var existing=await applications.FindActiveAsync(p.Id,c.Actor.CreatorId!.Value,ct);if(existing is not null)throw new ApplicationFailure(FailureKind.Validation,"Creator already has an active application.");CreatorApplication app;if(c.Platform is { } platform&&c.CreatorSocialProfileId is { } profileId){var slot=p.Platforms.SingleOrDefault(x=>x.Platform==platform);if(slot is null||slot.Available<=0)throw new ApplicationFailure(FailureKind.Validation,"This Promotion platform is unavailable.");app=new CreatorApplication(p.Id,c.Actor.CreatorId.Value,profileId,platform,c.Message,c.ContentConcept,p,c.Now,Guid.NewGuid());}else if(p.Platforms.Count>0)throw new ApplicationFailure(FailureKind.Validation,"Choose an eligible Promotion platform.");else app=new CreatorApplication(p.Id,c.Actor.CreatorId.Value,c.Message,c.ContentConcept,p,c.Now,Guid.NewGuid());await applications.AddAsync(app,ct);await events.PublishAsync([new CreatorApplied(p.Id,c.Actor.CreatorId.Value,c.Now,Guid.NewGuid())],ct);return app;}
 public async Task<CreatorAllocation> AssignAsync(AssignCreatorAllocationCommand c,CancellationToken ct){if(c.Actor.Role!=ActorRole.Business)throw new ApplicationFailure(FailureKind.Forbidden,"Only the owning Business may assign allocation.");var p=await promotions.GetAsync(c.PromotionId,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Promotion was not found.");if(p.BusinessId!=c.Actor.BusinessId)throw new ApplicationFailure(FailureKind.Forbidden,"Promotion belongs to another Business.");var approved=await applications.FindActiveAsync(p.Id,c.CreatorId,ct);if(approved?.Status!=CreatorApplicationStatus.Approved)throw new ApplicationFailure(FailureKind.Validation,"Creator must have an approved application before budget assignment.");try{var allocation=p.Allocate(c.CreatorId,c.Amount,c.Now,Guid.NewGuid(),approved.Platform,approved.CreatorSocialProfileId);await promotions.SaveAsync(p,c.ExpectedPromotionVersion,ct);await allocations.AddAsync(allocation,ct);await events.PublishAsync(p.DomainEvents,ct);return allocation;}catch(InvalidOperationException ex){throw new ApplicationFailure(FailureKind.Validation,ex.Message);}}
 public async Task IncreaseAsync(IncreaseCreatorAllocationCommand c,CancellationToken ct){if(c.Actor.Role!=ActorRole.Business)throw new ApplicationFailure(FailureKind.Forbidden,"Only the owning Business may increase allocation.");var a=await allocations.GetAsync(c.AllocationId,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Allocation was not found.");var p=await promotions.GetAsync(a.PromotionId,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Promotion was not found.");if(p.BusinessId!=c.Actor.BusinessId)throw new ApplicationFailure(FailureKind.Forbidden,"Promotion belongs to another Business.");try{p.IncreaseAllocation(a.Id,c.Amount,c.Now,Guid.NewGuid());await allocations.SaveAsync(a,c.ExpectedAllocationVersion,ct);await promotions.SaveAsync(p,p.Version-1,ct);await events.PublishAsync(p.DomainEvents,ct);}catch(InvalidOperationException ex){throw new ApplicationFailure(FailureKind.Validation,ex.Message);}}
 public async Task CompleteAsync(CompleteCreatorParticipationCommand c,CancellationToken ct){if(c.Actor.Role!=ActorRole.Business&&c.Actor.Role!=ActorRole.Creator)throw new ApplicationFailure(FailureKind.Forbidden,"Only a participant or owning Business may complete participation.");var a=await allocations.GetAsync(c.AllocationId,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Allocation was not found.");if(c.Actor.Role==ActorRole.Creator&&a.CreatorId!=c.Actor.CreatorId)throw new ApplicationFailure(FailureKind.Forbidden,"Allocation belongs to another Creator.");var p=await promotions.GetAsync(a.PromotionId,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Promotion was not found.");if(c.Actor.Role==ActorRole.Business&&p.BusinessId!=c.Actor.BusinessId)throw new ApplicationFailure(FailureKind.Forbidden,"Promotion belongs to another Business.");p.CompleteParticipation(a.Id,c.Now,Guid.NewGuid());await allocations.SaveAsync(a,c.ExpectedAllocationVersion,ct);await promotions.SaveAsync(p,p.Version-1,ct);await events.PublishAsync(p.DomainEvents,ct);}
}
