using Weymela.Domain;
namespace Weymela.Application;
public sealed record CreatePromotionCommand(Actor Actor, string Title, string Description, PromotionType Type, Money TotalBudget, CreatorEligibilityCriteria Eligibility, DateTime StartDateUtc, DateTime EndDateUtc, DateTime Now);
public sealed record FundPromotionCommand(Actor Actor, Guid PromotionId, long ExpectedPromotionVersion, long ExpectedWalletVersion, string IdempotencyKey, DateTime Now);
public sealed record PublishPromotionCommand(Actor Actor, Guid PromotionId, long ExpectedVersion, DateTime Now);
public sealed record ActivatePromotionCommand(Actor Actor, Guid PromotionId, long ExpectedVersion, DateTime Now);
public sealed record CompletePromotionCommand(Actor Actor, Guid PromotionId, long ExpectedVersion, DateTime Now);
public sealed record ApplyToPromotionCommand(Actor Actor, Guid PromotionId, string? Message, string? ContentConcept, CreatorVerifiedProfile Profile, DateTime Now);
public sealed record AssignCreatorAllocationCommand(Actor Actor, Guid PromotionId, Guid CreatorId, Money Amount, long ExpectedPromotionVersion, DateTime Now);
public sealed record CreditBusinessDepositCommand(Actor Actor, Money Amount, string IdempotencyKey, DateTime Now);
public sealed class PromotionApplicationService(IPromotionRepository promotions, IWalletRepository wallets, IFinancialConfigurationResolver pricing, IIdempotencyStore idempotency, IEventPublisher events, ILegalAcceptanceGate legal)
{
 public async Task<Promotion> CreateAsync(CreatePromotionCommand c, CancellationToken ct){Require(c.Actor,ActorRole.Business);await legal.EnsureCurrentAcceptedAsync(c.Actor.UserId,LegalRole.Business,[LegalDocumentType.BusinessAgreement,LegalDocumentType.AntiCircumventionAgreement],ct);var snapshot=await pricing.ResolveAsync(c.Type,c.Now,ct);try{var p=new Promotion(c.Actor.BusinessId!.Value,c.Title,c.Description,c.Type,c.TotalBudget,c.Eligibility,c.StartDateUtc,c.EndDateUtc,snapshot,c.Now);await promotions.AddAsync(p,ct);return p;}catch(ArgumentException ex){throw new ApplicationFailure(FailureKind.Validation,ex.Message);}}
 public async Task FundAsync(FundPromotionCommand c,CancellationToken ct){Require(c.Actor,ActorRole.Business);var prior=await ReplayAsync(c.IdempotencyKey,"FundPromotion",c.Actor,Fingerprint(c),ct);if(prior is not null)return;var p=await Owned(c.Actor,c.PromotionId,ct);var w=await wallets.GetAsync(c.Actor.BusinessId!.Value,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Business wallet was not found.");var effective=await pricing.ResolveAsync(p.PromotionType,c.Now,ct);if(effective.MinimumPromotionBudget is {} minimum && p.TotalBudget.Amount < minimum.Amount)throw new ApplicationFailure(FailureKind.Validation,"Campaign budget is below the effective type minimum.");if(w.AvailableBalance.Amount<p.TotalBudget.Amount)throw new ApplicationFailure(FailureKind.InsufficientFunds,"Available funds cannot fund this campaign.");try{p.Fund(w,c.Now,Guid.NewGuid());await wallets.SaveAsync(w,c.ExpectedWalletVersion,ct);await promotions.SaveAsync(p,c.ExpectedPromotionVersion,ct);await idempotency.SaveAsync(new(c.IdempotencyKey,"FundPromotion",c.Actor.UserId,Fingerprint(c),p.Id,c.Now),ct);await events.PublishAsync(p.DomainEvents,ct);}catch(InvalidOperationException ex) when(ex.Message.Contains("available",StringComparison.OrdinalIgnoreCase)){throw new ApplicationFailure(FailureKind.InsufficientFunds,ex.Message);}}
 public async Task PublishAsync(PublishPromotionCommand c,CancellationToken ct){Require(c.Actor,ActorRole.Business);var p=await Owned(c.Actor,c.PromotionId,ct);try{p.Publish(c.Now,Guid.NewGuid());await promotions.SaveAsync(p,c.ExpectedVersion,ct);await events.PublishAsync(p.DomainEvents,ct);}catch(InvalidOperationException ex){throw new ApplicationFailure(FailureKind.Validation,ex.Message);}}
 public async Task ActivateAsync(ActivatePromotionCommand c,CancellationToken ct){Require(c.Actor,ActorRole.Business);var p=await Owned(c.Actor,c.PromotionId,ct);try{p.Activate(c.Now,Guid.NewGuid());await promotions.SaveAsync(p,c.ExpectedVersion,ct);await events.PublishAsync(p.DomainEvents,ct);}catch(InvalidOperationException ex){throw new ApplicationFailure(FailureKind.Validation,ex.Message);}}
 public async Task CompleteAsync(CompletePromotionCommand c,CancellationToken ct){Require(c.Actor,ActorRole.Business);var p=await Owned(c.Actor,c.PromotionId,ct);var w=await wallets.GetAsync(c.Actor.BusinessId!.Value,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Business wallet was not found.");try{p.Complete(w,c.Now,Guid.NewGuid());await promotions.SaveAsync(p,c.ExpectedVersion,ct);await events.PublishAsync(p.DomainEvents,ct);}catch(InvalidOperationException ex){throw new ApplicationFailure(FailureKind.Validation,ex.Message);}}
 private async Task<Promotion> Owned(Actor a,Guid id,CancellationToken ct){var p=await promotions.GetAsync(id,ct)??throw new ApplicationFailure(FailureKind.NotFound,"Promotion was not found.");if(p.BusinessId!=a.BusinessId)throw new ApplicationFailure(FailureKind.Forbidden,"Promotion belongs to another Business.");return p;}
 private async Task<IdempotencyRecord?> ReplayAsync(string key,string op,Actor actor,string fingerprint,CancellationToken ct){if(string.IsNullOrWhiteSpace(key))throw new ApplicationFailure(FailureKind.Validation,"Idempotency key is required.");var prior=await idempotency.FindAsync(key,op,actor.UserId,ct);if(prior is null)return null;if(prior.OperationType!=op||prior.ActorId!=actor.UserId||prior.RequestFingerprint!=fingerprint)throw new ApplicationFailure(FailureKind.IdempotencyConflict,"Idempotency key conflicts with another request.");return prior;}
 private static string Fingerprint(FundPromotionCommand c) => RequestFingerprint.Create(c.Actor.BusinessId.ToString()!, c.PromotionId.ToString());private static void Require(Actor a,ActorRole role){if(a.Role!=role)throw new ApplicationFailure(FailureKind.Forbidden,"The actor is not authorized for this operation.");}
}
